import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function GhostCompareControls({ primaryName, primaryIsExample, otherDecks, ghostDeckId, ghost2DeckId, ghostDeckName, ghost2DeckName, onGhostDeckChange, onGhost2DeckChange, onSwap, }) {
    if (otherDecks.length === 0 && !ghostDeckId && !ghost2DeckId) {
        return null;
    }
    return (_jsxs("div", { className: "deck-sidebar-section deck-sidebar-section--tools deck-sidebar-tools", children: [otherDecks.length > 0 && (_jsxs("div", { className: "ghost-compare-section", children: [_jsx("label", { className: "ghost-compare-label", htmlFor: "ghost-deck-select", children: "Compare with" }), _jsxs("div", { className: "ghost-compare-row", children: [_jsxs("select", { id: "ghost-deck-select", value: ghostDeckId, onChange: (event) => onGhostDeckChange(event.target.value), children: [_jsx("option", { value: "", children: "None" }), otherDecks
                                        .filter((deck) => deck.id !== ghost2DeckId)
                                        .map((deck) => (_jsx("option", { value: deck.id, children: deck.name }, deck.id)))] }), ghostDeckId && (_jsx("button", { type: "button", className: "btn-swap", onClick: () => onSwap(1), children: "\u21C4 Swap primary" }))] }), _jsx("label", { className: "ghost-compare-label ghost-compare-label--secondary", htmlFor: "ghost2-deck-select", children: "And also" }), _jsxs("div", { className: "ghost-compare-row", children: [_jsxs("select", { id: "ghost2-deck-select", value: ghost2DeckId, onChange: (event) => onGhost2DeckChange(event.target.value), children: [_jsx("option", { value: "", children: "None" }), otherDecks
                                        .filter((deck) => deck.id !== ghostDeckId)
                                        .map((deck) => (_jsx("option", { value: deck.id, children: deck.name }, deck.id)))] }), ghost2DeckId && (_jsx("button", { type: "button", className: "btn-swap", onClick: () => onSwap(2), children: "\u21C4 Swap primary" }))] }), _jsx("p", { className: "ghost-compare-hint", children: "Ghost decks are view-only on the grid \u2014 edit the primary deck, then swap if needed." })] })), (ghostDeckId || ghost2DeckId) && (_jsxs("div", { className: "ghost-legend", children: [_jsxs("span", { className: "ghost-legend-item", children: [_jsx("span", { className: "ghost-swatch ghost-swatch-primary" }), primaryName, " (primary", primaryIsExample ? ', read-only' : ', editable', ")"] }), ghostDeckId && (_jsxs("span", { className: "ghost-legend-item", children: [_jsx("span", { className: "ghost-swatch ghost-swatch-ghost" }), ghostDeckName || '…', " (ghost, read-only)"] })), ghost2DeckId && (_jsxs("span", { className: "ghost-legend-item", children: [_jsx("span", { className: "ghost-swatch ghost-swatch-ghost2" }), ghost2DeckName || '…', " (ghost, read-only)"] }))] }))] }));
}
