export const actionDeck = {
  id: "example-action",
  name: "Action (AI generated)",
  createdAt: "2026-06-04T18:00:00.000Z",
  updatedAt: "2026-06-04T18:00:00.000Z",
  movies: [
    { id: "example-action-0", title: "Mad Max: Fury Road", fun: 9.8, good: 9.5 },
    { id: "example-action-1", title: "Top Gun: Maverick", fun: 9.5, good: 8.2 },
    { id: "example-action-2", title: "The Dark Knight", fun: 6.2, good: 9.9 },
    { id: "example-action-3", title: "Die Hard", fun: 9.2, good: 7.8 },
    { id: "example-action-4", title: "Mission: Impossible – Fallout", fun: 8.8, good: 8.5 },
    { id: "example-action-5", title: "Terminator 2: Judgment Day", fun: 8.5, good: 9 },
    { id: "example-action-6", title: "The Raid", fun: 7.5, good: 9.2 },
    { id: "example-action-7", title: "Casino Royale", fun: 7, good: 9.4 },
    { id: "example-action-8", title: "John Wick", fun: 8, good: 5.5 },
    { id: "example-action-9", title: "Kill Bill: Vol. 1", fun: 9, good: 6.8 },
    { id: "example-action-10", title: "Speed", fun: 7.8, good: 4.2 },
    { id: "example-action-11", title: "The Bourne Ultimatum", fun: 6.5, good: 8 },
    { id: "example-action-12", title: "Indiana Jones and the Last Crusade", fun: 8.2, good: 7 },
    { id: "example-action-13", title: "Black Panther", fun: 7.2, good: 7.5 },
    { id: "example-action-14", title: "Fast Five", fun: 9.5, good: 3.5 },
    { id: "example-action-15", title: "Heat", fun: 4.5, good: 9.6 },
    { id: "example-action-16", title: "Crouching Tiger, Hidden Dragon", fun: 5, good: 9.8 },
    { id: "example-action-17", title: "Wonder Woman", fun: 6.8, good: 6 },
    { id: "example-action-18", title: "Commando", fun: 8.5, good: 1.5 },
    { id: "example-action-19", title: "Transformers", fun: 5.5, good: 0.8 },
  ],
}
