export const comedyDeck = {
  id: "example-comedy",
  name: "Comedy (AI generated)",
  createdAt: "2026-06-04T18:00:00.000Z",
  updatedAt: "2026-06-04T18:00:00.000Z",
  movies: [
    { id: "example-comedy-0", title: "Airplane!", fun: 9.9, good: 7.5 },
    { id: "example-comedy-1", title: "Monty Python and the Holy Grail", fun: 9.5, good: 8.8 },
    { id: "example-comedy-2", title: "Groundhog Day", fun: 7, good: 9.5 },
    { id: "example-comedy-3", title: "Ghostbusters", fun: 9, good: 7.2 },
    { id: "example-comedy-4", title: "The Big Lebowski", fun: 8.5, good: 8 },
    { id: "example-comedy-5", title: "Superbad", fun: 9.2, good: 5.5 },
    { id: "example-comedy-6", title: "Office Space", fun: 8, good: 7.8 },
    { id: "example-comedy-7", title: "Borat", fun: 8.8, good: 6.5 },
    { id: "example-comedy-8", title: "Knives Out", fun: 6, good: 9 },
    { id: "example-comedy-9", title: "Bridesmaids", fun: 7.5, good: 7 },
    { id: "example-comedy-10", title: "When Harry Met Sally...", fun: 6.5, good: 8.5 },
    { id: "example-comedy-11", title: "Palm Springs", fun: 7.8, good: 8.2 },
    { id: "example-comedy-12", title: "Booksmart", fun: 7.2, good: 7.8 },
    { id: "example-comedy-13", title: "Dumb and Dumber", fun: 9.5, good: 2.5 },
    { id: "example-comedy-14", title: "The Hangover", fun: 8.2, good: 4 },
    { id: "example-comedy-15", title: "Step Brothers", fun: 9, good: 1.8 },
    { id: "example-comedy-16", title: "Anchorman", fun: 8.5, good: 3.2 },
    { id: "example-comedy-17", title: "Austin Powers: International Man of Mystery", fun: 7, good: 4.5 },
    { id: "example-comedy-18", title: "Ted", fun: 6.2, good: 2 },
    { id: "example-comedy-19", title: "Jackass Forever", fun: 8, good: 0.5 },
  ],
}
