export const dramaDeck = {
  id: "example-drama",
  name: "Drama (AI generated)",
  createdAt: "2026-06-04T18:00:00.000Z",
  updatedAt: "2026-06-04T18:00:00.000Z",
  movies: [
    { id: "example-drama-0", title: "The Shawshank Redemption", fun: 6.5, good: 9.8 },
    { id: "example-drama-1", title: "The Godfather", fun: 3.5, good: 10 },
    { id: "example-drama-2", title: "Parasite", fun: 7, good: 9.6 },
    { id: "example-drama-3", title: "Schindler's List", fun: 0.5, good: 9.9 },
    { id: "example-drama-4", title: "Moonlight", fun: 2, good: 9.5 },
    { id: "example-drama-5", title: "12 Years a Slave", fun: 0.8, good: 9.4 },
    { id: "example-drama-6", title: "Whiplash", fun: 8, good: 9.2 },
    { id: "example-drama-7", title: "The Social Network", fun: 6, good: 9 },
    { id: "example-drama-8", title: "A Separation", fun: 1.5, good: 9.7 },
    { id: "example-drama-9", title: "Lady Bird", fun: 7.5, good: 8.5 },
    { id: "example-drama-10", title: "The Florida Project", fun: 2.5, good: 9 },
    { id: "example-drama-11", title: "Brokeback Mountain", fun: 3, good: 8.8 },
    { id: "example-drama-12", title: "Manchester by the Sea", fun: 1, good: 9.1 },
    { id: "example-drama-13", title: "Marriage Story", fun: 2.8, good: 8.6 },
    { id: "example-drama-14", title: "Room", fun: 1.8, good: 8.9 },
    { id: "example-drama-15", title: "Nomadland", fun: 2.2, good: 8.2 },
    { id: "example-drama-16", title: "Forrest Gump", fun: 9, good: 6.5 },
    { id: "example-drama-17", title: "Titanic", fun: 8.5, good: 7 },
    { id: "example-drama-18", title: "The Tree of Life", fun: 0.3, good: 8.5 },
    { id: "example-drama-19", title: "Requiem for a Dream", fun: 0.2, good: 9.3 },
  ],
}
